// Code generated by counterfeiter. DO NOT EDIT.
package commandfakes

import (
	sync "sync"

	command "code.cloudfoundry.org/cli/command"
)

type FakeSharedActor struct {
	CheckTargetStub        func(bool, bool) error
	checkTargetMutex       sync.RWMutex
	checkTargetArgsForCall []struct {
		arg1 bool
		arg2 bool
	}
	checkTargetReturns struct {
		result1 error
	}
	checkTargetReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSharedActor) CheckTarget(arg1 bool, arg2 bool) error {
	fake.checkTargetMutex.Lock()
	ret, specificReturn := fake.checkTargetReturnsOnCall[len(fake.checkTargetArgsForCall)]
	fake.checkTargetArgsForCall = append(fake.checkTargetArgsForCall, struct {
		arg1 bool
		arg2 bool
	}{arg1, arg2})
	fake.recordInvocation("CheckTarget", []interface{}{arg1, arg2})
	fake.checkTargetMutex.Unlock()
	if fake.CheckTargetStub != nil {
		return fake.CheckTargetStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.checkTargetReturns
	return fakeReturns.result1
}

func (fake *FakeSharedActor) CheckTargetCallCount() int {
	fake.checkTargetMutex.RLock()
	defer fake.checkTargetMutex.RUnlock()
	return len(fake.checkTargetArgsForCall)
}

func (fake *FakeSharedActor) CheckTargetCalls(stub func(bool, bool) error) {
	fake.checkTargetMutex.Lock()
	defer fake.checkTargetMutex.Unlock()
	fake.CheckTargetStub = stub
}

func (fake *FakeSharedActor) CheckTargetArgsForCall(i int) (bool, bool) {
	fake.checkTargetMutex.RLock()
	defer fake.checkTargetMutex.RUnlock()
	argsForCall := fake.checkTargetArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeSharedActor) CheckTargetReturns(result1 error) {
	fake.checkTargetMutex.Lock()
	defer fake.checkTargetMutex.Unlock()
	fake.CheckTargetStub = nil
	fake.checkTargetReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeSharedActor) CheckTargetReturnsOnCall(i int, result1 error) {
	fake.checkTargetMutex.Lock()
	defer fake.checkTargetMutex.Unlock()
	fake.CheckTargetStub = nil
	if fake.checkTargetReturnsOnCall == nil {
		fake.checkTargetReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.checkTargetReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeSharedActor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.checkTargetMutex.RLock()
	defer fake.checkTargetMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSharedActor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ command.SharedActor = new(FakeSharedActor)
